FUNCTION fin_kontni_plan_2022()

    LOCAL cStarted := fetch_metric( "f18_kontni_2022", NIL, "0" )
    LOCAL cDatabase
    LOCAL aKontaPromjenaNaziva := {;
          { "01", "Nematerijalna sredstva", "Nematerijalna imovina" }, ;
          { "03", "Investicijske nekretnine", "Ulaganja u investicijske nekretnine" }, ;
          { "04", "Biološka sredstva", "Biološka imovina" }, ;
          { "045", "Biološka sredstva u pripremi", "Biološka imovina u pripremi" }, ;
          { "047", "Avansi za biološka sredstva", "Avansi za biološku imovinu" }, ;
          { "065", "Finansijska sredstva raspoloživa za prodaju", "Finansijska imovina po fer vrijednosti kroz ostali ukupni rezultat" }, ;
          { "066", "Finansijska sredstva koja se drže do roka dospijeća", "Finansijska imovina po amortizovanom trošku" }, ;
          { "07", "Druga dugoročna potraživanja", "Ostala dugoročna potraživanja i imovina"},;
          { "078", "Ostala dugoročna potraživanja", "Ostala dugoročna potraživanja i imovina"},;
          { "079", "Ispravka vrijednosti dugoročnih potraživanja", "Ispravka vrijednosti dugoročnih potraživanja i imovine"},;
          { "09", "Odgođena porezna sredstva i dugoročna razgraničenja", "Odgođena porezna imovina i dugoročna razgraničenja"},;
          { "090", "Odgođena porezna sredstva", "Odgođena porezna imovina"},;
          { "091", "Unaprijed plaćeni troškovi (za period dužio od 12 mj)", "Unaprijed plaćeni troškovi"},;
          { "098", "Ostala dugoročna razgraničenja", "Ostala dugoročna razgraničenja"},;
          { "14", "Stalna sredstva i sredstva obustavljenog poslovanja namjenjena prodaji", "Dugoročna imovina namjenjena prodaji i imovina poslovanja koje se obustavlja"},;
          { "145", "Biološka sredstva namjenjena prodaji", "Biološka imovina namjenjena prodaji"},;
          { "147", "Sredstva obustavljenog poslovanja namjenjena prodaji", "Imovima poslovanja koje se obustavlja"},;
          { "149", "Ispravka vrijednosti sredstava namjenjenih prodaji i obustavljenog poslovanja", "Ispravka vrijednosti dugoročne imovine namjenjene prodaji i imovine poslovanja koje se obustavlja"},;
          { "150", "Dati avansi za zalihe i usluge povezanim pravnim licima", "Dati avansi za zalihe povezanim stranama"},;
          { "151", "Dati avansi za zalihe i usluge ostalim pravnim licima", "Dati avansi za zalihe nepovezanim stranama"},;
          { "20", "Gotovina i gotovinski ekvivalenti", "Novac i novčani ekvivalenti"},;
          { "207", "Gotovinski ekvivalenti", "Novčani ekvivalenti"},;
          { "209", "Oročena novčana sredstva", "Ispravka vrijednosti novca i novčanih ekvivalenata"},;
          { "210", "Kupci - povezana pravna lica", "Kupci - povezane strane"},;
          { "23", "Druga kratkoročna potraživanja", "Ostala kratkoročna potraživanja"},;
          { "245", "Finansijska sredstva namijenjena trgovanju", "Finansijska imovina po fer vrijednosti kroz bilans uspjeha"},;
          { "278", "Druga potraživanja iz osnova PDV-a", "Ostala potraživanja po osnovu PDV-a"},;
          { "30", "Osnovni kapital", "Vlasnički kapital"},;
          { "320", "Emisiona premija", "Dionička premija"},;
          { "321", "Zakonske rezerve", "Statutarne rezerve"},;
          { "322", "Statutarne i druge rezerve", "Ostale rezerve"},;
          { "33", "Revalorizacijske rezerve i nerealizovani dobici i gubici", "Revalorizacione rezerve"},;
          { "330", "Revalorizacijske rezerve iz osnova revalorizacije stalnih sredstava", "Revalorizacione rezerve za nekretnine, postrojenja i opremu i nematerijalnu imovinu"},;
          { "331", "Razlike nastale prevođenjem finansijskih izvještaja u valutu prezentacije", "Efekti revalorizacije proizašli iz transakcija zaštite"},;
          { "332", "Nerealizovani gubici iz osnova finansijskih sredstava raspoloživih za prodaju", "Revalorizacione rezerve za finansijsku imovinu po fer vrijednosti kroz ostali ukupni rezultat"},;
          { "339", "Ostale revalorizacijske rezerve i nerealizovano dobici i gubidi", "Ostale revalorizacione rezerve"},;
          { "34", "Neraspoređena dobit", "Dobit"},;
          { "340", "Neraspoređena dobit", "Neraspoređena dobiti ranijih perioda"},;
          { "341", "Neraspoređena dobit", "Neraspoređena dobit izvještajnog perioda"},;
          { "35", "Gubitak do visine kapitala", "Gubitak"},;
          { "350", "Gubitak ranijih godina", "Gubitak ranijih perioda"},;
          { "351", "Gubitak izvještajne godine", "Gubitak izvještajnog perioda"},;
          { "36", "Otkupljene vlastite dionice i udjeli", "Otkupljene vlastite dionice"},;
          { "360", "Otkupljene vlastite dionice i udjeli", "Otkupljene vlastite dionice"},;
          { "40", "Dugoročna rezervisanja i odložene porezne obaveze", "Dugoročna rezervisanja i razgraničenja i odgođene porezne obaveze"},;
          { "402", "Rezervisanja za zadržane kaucije i depozite", "Obaveze za zadržane kaucije i depozite"},;
          { "407", "Unaprijed naplaćeni i drugi odloženi prihodi", "Unaprijed naplaćeni, odgođeni priodi"},;
          { "410", "Obaveze koje se mogu konvertovati u kapital", "Obaveze koje se mogu konvertovati u kapital"},;
          { "412", "Obaveze po emitovanim ...", "Obaveze po izdatim dužničkim instrumentima"},;
          { "421", "...", "Obaveze po izdatim dužničkim instrumentima" }, ;
          { "422", "...", "Kratkoročni krediti uzeti u zemlji" }, ;
          { "423", "...", "Kratkoročni krediti uzeti u inostranstvu" }, ;
          { "424", "...", "Prekoračenja po bankovnim računima" }, ;
          { "425", "...", "Kratkoročne obaveze po najmovima (finansijski najam)" }, ;
          { "426", "...", "Kratkoročne obaveze po najmovima (operativni najam)" }, ;
          { "427", "...", "Finansijske obaveze po fer vrijednosti kroz bilans uspjeha" }, ;
          { "428", "...", "Ostale kratkoročne finansijske obaveze po amortizovanom trošku" }, ;
          { "430", "...", "Primljeni depoziti i kaucije i zadržana plaćanja" }, ;
          { "431", "...", "Dobavljači - povezane strane" }, ;
          { "462", "Obaveze za učešće u dobiti", "Obaveze za raspodjelu dobiti" }, ;
          { "533", "Troškovi zakupa", "Troškovi najma" }, ;
          { "543", "Troškovi rezervisanja iz osnova datih garantnih rokova", "Troškovi rezervisanja po osnovu datih garantnih rokova" }, ;
          { "549", "Troškovi ostalih dugoročnih rezervisanja", "Troškovi ostalih rezervisanja" }, ;
          { "550", "Troškovi neproizvodnih usluga", "Troškovi ostalih usluga" }, ;
          { "570", "...", "Gubici od otuđenja nematerijalne imovine, nekretnina, postrojenja i oprema" }, ;
          { "571", "...", "Gubici od otuđenja investicijskih nekretnina" }, ;
          { "572", "...", "Gubici od otuđenja biološke imovine" }, ;
          { "573", "...", "Gubici od otuđenja dugoročne imovine namjenjene prodaji i imovine poslovanja koje se obustavlja" }, ;
          { "574", "...", "Gubici od otuđenja finansijske imovine i ulaganja u povezane strane" }, ;
          { "577", "...", "Gubici od derivatnih finansijskih instrumenata" }, ;
          { "579", "...", "Rashodovanja na zalihama materijala i robe, ostali rashodi" }, ;
          { "58", "...", "Rashodi/gubici po osnovu umanjenja vrijednosti imovine" }, ;
          { "580", "...", "Umanjenje vrijednosti nematerijalne imovine" }, ;
          { "581", "...", "Umanjenje vrijednosti nekretnina, postrojenja i opreme" }, ;
          { "582", "...", "Umanjenje vrijednosti investicijsih nekretnina koje se vode po trošku" }, ;
          { "583", "...", "Umanjenje vrijednosti biološke imivine koja se vodi po trošku" }, ;
          { "584", "...", "Gubici od usklađivanja vrijednosti dugoročne finansijske imovine" }, ;
          { "585", "...", "Gubici od usklađivanja vrijednosti zaliha" }, ;
          { "586", "...", "Gubici od usklađivanja vrijednosti kratkoročne finansijske imovine" }, ;
          { "588", "...", "Gubici od usklađivanja vrijednosti dugoročne imovine namijenjene prodaji i imovine poslovanja koje se obustavlja" }, ;
          { "589", "...", "Gubici od usklađivanja vrijednosti ostale finansijske i nefinansijske imovine" }, ;
          { "59", "...", "Efekti promjena računovosdstvenih politika i ispravki grešaka iz ranijih perioda, promjena vrijednosti zaliha i prenos rashoda" }, ;
          { "590", "...", "Rashodi po osnovu promjene računovodstvenih politika" }, ;
          { "591", "...", "Rashodi po osnovu ispravki grešaka iz ranijih perioda" }, ;
          { "595", "...", "Povećanje vrijednosti zaliha gotovih proizvoda, poluproizvoda i proizvodnje u toku" }, ;
          { "596", "...", "Smanjenje vrijednosti zaliha gotovih proizvoda, poluproizvoda i proizvodnje u toku" }, ;
          { "600", "...", "Prihodi od prodaje povezanim stranama" }, ;
          { "601", "...", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu" }, ;
          { "602", "...", "Prihodi od prodaje nepovezanim stranama na inostranom tržištu" }, ;
          { "61", "...", "Prihodi od prodaje gotovih proizvoda" }, ;
          { "610", "...", "Prihodi od prodaje povezanim stranama" }, ;
          { "611", "...", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu" }, ;
          { "612", "...", "Prihodi od prodaje nepovezanim stranama na inostranom tržištu" }, ;
          { "64", "...", "Promjena fer vrijednosti dugoročne nefinansijske imovine" }, ;
          { "640", "...", "Povećanje fer vrijednosti investicijskih nekretnina koja se ne amortizuju" }, ;
          { "641", "...", "Povećanje fer vrijednosti biološke imovine koja se ne amortizuje" }, ;
          { "643", "...", "Smanjenje fer vrijednosti investicijskih nekretnina koja se ne amortizuju" }, ;
          { "644", "...", "Smanjenje fer vrijednosti biološke imovine koja se ne amortizuje" }, ;
          { "651", "...", "Prihodi od najma" }, ;
          { "661", "...", "Prihodi od kamata od nepovezanih strana" }, ;
          { "663", "...", "Prihodi po osnovu valutne klauzule" }, ;
          { "677", "...", "Naplaćena ranije otpisana potraživanja" }, ;
          { "678", "...", "Dobici od derivatnih finansijskih instrumenata" }, ;
          { "68", "...", "Prihodi-dobici po osnovu usklađivanja vrijednosti imovine" }, ;
          { "680", "...", "Dobici od otpuštanja ranije priznatih gubitaka od umanjenja vrijednosti nematerijalne imovine" }, ;
          { "681", "...", "Dobici od nekretnina, postrojenja i opreme" }, ;
          { "682", "...", "Dobici od otpuštanja ranije priznatih gubitaka od umanjenja vrijednosti investicijskih nekretnina koje se vode po trošku" }, ;
          { "683", "...", "Dobici od otpuštanja ranije priznatih gubitaka od umanjenja vrijednosti biološke imovine koja se vodi po trošku" }, ;
          { "684", "...", "Dobici od usklađivanja vrijednosti dugoročne finansijske imovine" }, ;
          { "685", "...", "Dobici od usklađivanja vrijednosti zaliha" }, ;
          { "686", "...", "Dobici od usklađivanja vrijednosti kratkoročne finansijske imovine" }, ;
          { "687", "...", "Dobici od prestanka priznavanja imovine s pravom korištenja" }, ;
          { "688", "...", "Dobici od usklađivanja vrijednosti dugoročne imovine namijenjene prodaji imovine poslovanja koje se obustavlja" }, ;
          { "689", "...", "Dobici od usklađivanja vrijednosti ostale finansijske i nefinansijske imovine" }, ;
          { "69", "...", "Efekti promjena računovodstvenih politika i ispravki grešaka iz ranijih perioda i prenos prihoda" }, ;
          { "690", "...", "Prihodi po osnovu promjene računovodstvenih politika" }, ;
          { "691", "...", "Prihodi po osnovu ispravki grešaka iz ranijih perioda" } ;
       }

    LOCAL aKontaNova := {;
        { "046", "Vrijednosna usklađivanja biološke imovine po osnovu promjene fer vrijednosti"},;
        { "048", "Vrijednosna usklađivanja biološke imovine po osnovu umanjenja vrijednosti"},;
        { "049", "Ispravka vrijednosti biološke imovine"},;
        { "05", "Imovina s pravom korištenja"},; // nakon preknjiženja stare klase 05
        { "050", "Zemljište"},;
        { "051", "Građevinski objekti"},;
        { "052", "Postrojenja i oprema (mašine)"},;
        { "053", "Nematerijalna imovina"},;
        { "059", "Ispravka vrijednosti imovine s pravom korištenja"},;
        { "0651", "Instrumenti kapitala (dionice i vlasnički udjeli)" }, ;
        { "0652", "Dužnički instrumenti (obveznice, dati krediti, depoziti kod banaka)" }, ;
        { "0653", "Ostala finansijska imovina po fer vrijednosti kroz ostali ukupni rezultat" }, ;
        { "0654", "Potraživanja za kamatu od finansijske imovine po fer vrijednosti kroz ostali ukupni rezultat" }, ;
        { "0658", "Vrijednosna usklađivanja dugoročne finansijske imovine po fer vrijednosti kroz ostali ukupni rezultat po osnovu promjene fer vrijednosti" }, ;
        { "0659", "Ispravka vrijednosti dugoročne finansijske imovine po fer vrijednosti kroz ostali ukupni rezultat" }, ;
        { "0661", "Depoziti kod banaka" }, ;
        { "0663", "Obveznice" }, ;
        { "0664", "Ostala finansijska imovina po amortizovanom trošku" }, ;
        { "0669", "Ispravka vrijednosti dugoročne finansijske imovine po amortizovanom trošku" }, ;
        { "070", "Ostala dugoročna imovina po osnovu ugovora sa kupcima - dodatni troškovi sticanja ugovora" }, ;
        { "071", "Ostala dugoročna imovina po osnovu ugovora sa kupcima - troškovi izvršenja ugovora" }, ;
        { "0791", "Ispravka vrijednosti dugoročne imovine po osnovu ugovora sa kupcima" }, ;
        { "02", "Ispravka vrijednosti dugoročne imovine po osnovu ugovora sa kupcima" }, ;
        { "22", "Derivatna finansijska imovina" }, ;
        { "220", "Derivatna finansijska imovina koja se koristi kao instrument zaštite" }, ;
        { "221", "Ostala derivatna finansijska imovina" }, ;
        { "237", "Potraživanja po osnovu faktoring poslova" }, ;
        { "247", "Potraživanja po finansijskim najmovima" }, ;
        { "2471", "Kratkoročna potraživanja po finansijskim najmovima" }, ;
        { "2479", "Ispravka vrijednosti kratkoročnih potraživanja po finansijskim najmovima" }, ;
        { "3200", "Ažio" }, ;
        { "3201", "Disažio" }, ;
        { "418", "Ostale dugoročne finansijske obaveze po amortizovanom trošku" }, ;
        { "44", "Derivatne finansijske obaveze" }, ;
        { "440", "Derivatne finansijske obaveze proistekle iz instrumenata zaštite" }, ;
        { "441", "Ostale derivatne finansijske obaveze" }, ;
        { "4600", "Obaveze po osnovu kamata po uzetim kreditima" }, ;
        { "4601", "Obaveze po osnovu kamata po najmovima" }, ;
        { "4602", "Obaveze po osnovu kamata po izdatim dužničkim instrumentima" }, ;
        { "4603", "Obaveze po osnovu kamata po ostalim finansijskim obavezama po amortizovanom trošku" }, ;
        { "5730", "Gubici od otuđenja dugoročne imovine namjenjene prodaji" }, ;
        { "5730", "Gubici od otuđenja imovine poslovanja koje se obustavlja" }, ;
        { "5740", "Gubici od otuđenja finansijske imovine po amortizovanom trošku" }, ;
        { "5741", "Gubici od otuđenja finansijske imovine po fer vrijednosti kroz ukupni rezultat" }, ;
        { "5742", "Gubici od otuđenja finansijske imovine po fer vrijednosti kroz bilans uspjeha" }, ;
        { "5743", "Gubici od otuđenja ulaganja u zavisna društva" }, ;
        { "5744", "Gubici od otuđenja ulaganja u pridružena društva" }, ;
        { "5745", "Gubici od otuđenja ulaganja u zajedničke poduhvate" }, ;
        { "5780", "Direktan otpis potraživanja od kupaca" }, ;
        { "5781", "Ispravka vrijednosti i otpis ostale imovine i potraživanja koji nisu finansijska imovina" }, ;
        { "5810", "Umanjenje vijednosti nekretnina, postrojenja i opreme koji se vode po trošku" }, ;
        { "5811", "Gubici od promjene revalorizovane vrijednosti nekretnina, postrojenja i opreme za koje nema postojećih revalorizacionih rezervi" }, ;
        { "5841", "Kreditni gubici od finansijske imovine po amortizovanom trošku" }, ;
        { "5842", "Kreditni gubici od finansijske imovine po fer vrijednosti kroz ukupni rezultat" }, ;
        { "5843", "Gubici od prestanka priznavanja finansijske imovine po amortizovanom trošku (usljed modifikacije)" }, ;
        { "5844", "Gubici od modifikacije finansijske imovine po amortizovanom trošku koje nisu rezultirale prestankom priznavanja" }, ;
        { "5845", "Gubici od reklasifikacija finansijske imovine između poslovnih modela" }, ;
        { "5860", "Kreditni gubici od potraživanja od kupaca" }, ;
        { "5861", "Kreditni gubici od ostale finansijske imovine po amortizovanom trošku" }, ;
        { "5862", "Smanjenje vrijednosti finansijske imovine po fer vrijednosti kroz bilans uspjeha" }, ;
        { "587", "Gubici od prestanka priznavanja imovine s pravom korištenja" }, ;
        { "5880", "Gubici od usklađivanja vrijednosti dugoročne imovine namijenjenje prodaji" }, ;
        { "5881", "Gubici od usklađivanja vrijednosti imovine poslovanja koje se obustavlja" }, ;
        { "6001", "Prihodi od prodaje povezanim stranama priznati u momentu transakcije" }, ;
        { "6002", "Prihodi od prodaje povezanim stranama tokom vremena" }, ;
        { "6011", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu priznati u momentu transakcije" }, ;
        { "6012", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu priznati tokom vremena" }, ;
        { "6021", "Prihodi od prodaje nepovezanim stranama na inostranom tržištu priznati u momentu transakcije" }, ;
        { "6022", "Prihodi od prodaje nepovezanim stranaam na inostranom tržištu priznati tokom vremena" }, ;
        { "603", "Odobreni popusti i rabati" }, ;
        { "6101", "Prihodi od prodaje povezanim stranama priznati u momentu transakcije" }, ;
        { "6102", "Prihodi od prodaje povezanim stranama priznati tokom vremena" }, ;
        { "6111", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu priznati u momentu transakcije" }, ;
        { "6112", "Prihodi od prodaje nepovezanim stranama na domaćem tržištu priznati tokom vremena" }, ;
        { "6121", "Prihodi od prodaje nepovezanim stranama na inostranom tržištu priznati u momentu transakcije" }, ;
        { "6122", "Prihodi od prodaje nepovezanim stranama na inostranom tržištu priznati tokom vremena" }, ;
        { "613", "Odobreni popusti i rabati" }, ;
        { "62", "Prihodi od pruženih usluga" }, ;
        { "620", "Prihodi od pruženih usluga povezanim stranama" }, ;
        { "6201", "Prihodi od pruženih usluga povezanim stranama priznati u momentu transakcije" }, ;
        { "6202", "Prihodi od pruženih usluga povezanim stranama priznati tokom vremena" }, ;
        { "621", "Prihodi od pruženih usluga nepovezanim stranama na domaćem tržištu" }, ;
        { "6211", "Prihodi od pruženih usluga nepovezanim stranama na domaćem tržištu priznati u momentu transakcije" }, ;
        { "6212", "Prihodi od pruženih usluga nepovezanim stranama na domaćem tržištu priznati tokom vremena" }, ;
        { "622", "Prihodi od pruženih usluga nepovezanim stranama na inostranom tržištu" }, ;
        { "6221", "Prihodi od pruženih usluga nepovezanim stranama na inostranom tržištu priznati u momentu transakcije" }, ;
        { "6222", "Prihodi od pruženih usluga nepovezanim stranama na inostranom tržištu priznati tokom vremena" }, ;
        { "623", "Odobreni popusti i rabati" }, ;
        { "656", "Prihodi od dividendi" }, ;
        { "660", "Prihodi od kamata od povezanih strana" }, ;
        { "6730", "Dobici od otuđenja dugoročne imovine namijenjene prodaji" }, ;
        { "6731", "Dobici od otuđenja imovine poslovanja koje se obustavlja" }, ;
        { "6740", "Dobici od otuđenja finansijske imovine po amortizovanom trošku" }, ;
        { "6741", "Dobici od otuđenja finansijske imovine po fer vrijednosti kroz ukupni rezultat" }, ;
        { "6742", "Dobici od otuđenja finansijske imovine po fer vrijednosti kroz bilans uspjeha" }, ;
        { "6743", "Dobici od otuđenja u zavisna društva" }, ;
        { "6744", "Dobici od otuđenja u pridružena društva" }, ;
        { "6745", "Dobici od otuđenja u zajedničke poduhvate" }, ;
        { "6810", "Dobici od otpuštanja ranije priznatih gubitaka od umanjenja vrijednosti nekretnina, postrojenja i opreme koji se vode po trošku" }, ;
        { "6811", "Dobici od otpuštanja ranije priznatih gubitaka od promjene revalorizovane vrijednosti nekretnina, postrojenja i opreme za koje nema postojećih revalorizacionih rezervi" }, ;
        { "6841", "Dobici od otpuštanja ranije priznatih kreditnih gubitaka od finsnsijske imovine po amortizovanom trošku" }, ;
        { "6842", "Dobici od otpuštanja ranije priznatih kreditnih gubitaka od finsnsijske imovine po fer vrijednosti kroz ukupni rezultat" }, ;
        { "6843", "Dobici od prestanka priznavanja finansijske imovine po amortizovanom trošku (usljed modifikacije)" }, ;
        { "6844", "Dobici od modifikacija finansijske imovine po amortizovanom trošku koje nisu rezultirale prestankom priznavanja" }, ;
        { "6845", "Dobici od reklasifikacija finansijske imovine između poslovnih modela" }, ;
        { "6861", "Dobici od otupštanja ranije priznatih kreditnih gubitaka od ostale finansijske imovine po amortizovanom trošku" }, ;
        { "6862", "Povećanje vrijednosti finansijske imovine po fer vrijednosti kroz bilans uspjeha" }, ;
        { "6880", "Dobici od usklađivanja vrijednosti dugoročne imovine namijenjene prodaji" }, ;
        { "6881", "Dobici od usklađivanja vrijednosti imovine poslovanja koje se obustavlja" } ;
    }

    LOCAL aKontaBrisati := {;
        { "22"  },;
        { "222" },;
        { "223" },;
        { "228" },;
        { "229" },;
        { "241", "Kratkoročni krediti dati u zemlji"},;
        { "242", "Kratkoročni krediti dati u inostranstvu"},;
        { "243", "Kratkoročni dio dugoročnih kredita"},;
        { "244", "Kratkoročni dio dugoročnih vrjednostnih papira"},;
        { "246", "Druga finansijska sredstva označena po fer vrijednosti"},;
        { "248", "Ostali kratkoročni finansijski plasmani"},;
        { "249", "Ispravka vrijednosti kratkoročnih finansijskih plasmana"},;
        { "303", "Zadružni udjeli"},;
        { "304", "Ulozi"},;
        { "333", "Nerealizovani gubici iz osnova finansijskih sredstava raspoloživih za prodaju"};
    }

    LOCAL aKontaPreknj := { ;
            {"013", "Ulaganja na tuđim sredstvima",;
              {;
                { "0201", "Ulaganja u tuđe zemljište" },;
                { "0211", "Ulaganja u tuđe građevinske objekte" } ;
              };    
            },;
            { "026", "Stambene zgrade i stanovi", ;
               {;
                  { "0212", "Stambene zgrade i stanovi" } ;
               };
            },;
            { "01?8", "Vrijednosna usklađivanja nematerijalne imovine po osnovu umanjenja vrijednosti", ;
               {;
                  { "018", "Vrijednosna usklađivanja nematerijalne imovine po osnovu umanjenja vrijednosti" }, ;
                  { "019", "Ispravka vrijednosti nematerijalne imovine" } ;
               };
            },;
            { "01?9", "Ispravka vrijednosti nematerijalne imovine", ;
                {;
                   { "018", "Vrijednosna usklađivanja nematerijalne imovine po osnovu umanjenja vrijednosti" }, ;
                   { "019", "Ispravka vrijednosti nematerijalne imovine" } ;
                };
            },;
            { "03?8", "-pogledaj-stari-kontni-plan", ;
                {;
                    { "036", "Vrijednosna usklađivanja ulaganja u investicijske nekretnine po osnovu promjene fer vrijednosti" }, ;
                    { "038", "Vrijednosna usklađivanja ulaganja u investicijske nekretnine po osnovu umanjenja vrijednosti" }, ;
                    { "039", "Ispravka vrijednosti ulaganja u investicijske nekretnine" }, ;
                };
            },;
            { "03?9", "-pogledaj-stari-kontni-plan", ;
                {;
                    { "036", "Vrijednosna usklađivanja ulaganja u investicijske nekretnine po osnovu promjene fer vrijednosti" }, ;
                    { "038", "Vrijednosna usklađivanja ulaganja u investicijske nekretnine po osnovu umanjenja vrijednosti" }, ;
                    { "039", "Ispravka vrijednosti ulaganja u investicijske nekretnine" }, ;
                };
            },; 
            { "04?8", "-pogledaj-stari-kontni-plan", ;
                {;
                    { "046", "Vrijednosna usklađivanja ulaganja biološke imovine po osnovu promjene fer vrijednosti" }, ;
                    { "048", "Vrijednosna usklađivanja ulaganja biološke imovine po osnovu umanjenja vrijednosti" }, ;
                    { "049", "Ispravka vrijednosti biološke imovine" }, ;
                };
            },;
            { "04?9", "-pogledaj-stari-kontni-plan", ;
                {;
                    { "046", "Vrijednosna usklađivanja ulaganja biološke imovine po osnovu promjene fer vrijednosti" }, ;
                    { "048", "Vrijednosna usklađivanja ulaganja biološke imovine po osnovu umanjenja vrijednosti" }, ;
                    { "049", "Ispravka vrijednosti biološke imovine" }, ;
                };
            },;
            { "05?", "Ostala stalna materijalna sredstva", ;
                {;
                    { "026", "Ostala dugoročna materijalna sredstva" }, ;
                    { "078", "Ostala dugoročna potraživanja i imovina" } ;
                };
            },;
            { "061", "Učešća u kapitalu drugih pravnih lica", ;
                {;
                    { "060", "Ulaganja u zavisna i pridružena društva i zajedničke poduhvate" } ;
                };
            },;
            { "062", "Dugoročni krediti dati povezanim pravnim licima", ;
                {;
                    { "0662", "Dati krediti" } ;
                };
            },;
            { "063", "Dugoročni krediti dati u zemlji", ;
                {;
                    { "0662", "Dati krediti" } ;
                };
            },;
            { "064", "Dugoročni krediti dati u inostranstvo", ;
                {;
                    { "0662", "Dati krediti" } ;
                };
            },;
            { "070", "Potraživanja od povezanih pravnih lica", ;
                {;
                    { "067", "Potraživanja po finansijskim najmovima" }, ;
                    { "0671", "Dugoročna potraživanja po finansijskim najmovima" }, ;
                    { "0679", "Ispravka vrijednosti dugoročnih potraživanja po finansijskim najmovima" }, ;
                };
            },; 
            { "071", "Potraživanja po osnovu prodaje na kredit", ;
                {;
                    { "067", "Potraživanja po finansijskim najmovima" }, ;
                    { "0671", "Dugoročna potraživanja po finansijskim najmovima" }, ;
                    { "0679", "Ispravka vrijednosti dugoročnih potraživanja po finansijskim najmovima" }, ;
                };
            },;            
            { "072", "Potraživanja po ugovorima o finansijskom najmu (lizingu)", ;
                {;
                    { "067", "Potraživanja po finansijskim najmovima" }, ;
                    { "0671", "Dugoročna potraživanja po finansijskim najmovima" }, ;
                    { "0679", "Ispravka vrijednosti dugoročnih potraživanja po finansijskim najmovima" }, ;
                };
            },;
            { "220", "Potraživanja od izvoznika", ;
                {;
                    { "X220", "X? Potraživanja od izvoznika" } ;
                };
            },;
            { "221", "Potraživanja po osnovu uvoza za tuđi račun", ;
                {;
                    { "X221", "X? Potraživanja po osnovu uvoza za tuđi račun" } ;
                };
            },;
            { "222", "Potraživanja po osnovu konsignacione i komisione prodaje", ;
                {;
                    { "X222", "X? Potraživanja po konsignacione i komisione prodaje" } ;
                };
            },;
            { "223", "Potraživanja iz zajedničkih poslova", ;
                {;
                    { "X223", "X? Potraživanja iz zajedničkih poslova" } ;
                };
            },;
            { "228", "Ostala potraživanja iz specifičnih poslova", ;
                {;
                    { "X228", "X? Ostala potraživanja iz specifičnih poslova" } ;
                };
            },;
            { "229", "Ispravka vrijednosti potraživanja iz specifičnih poslova", ;
                {;
                    { "X228", "X? Ispravka vrijednosti potraživanja iz specifičnih poslova" } ;
                };
            },;
            { "230", "Potraživanja za kamatu i dividendu od povezanih pravnih lica", ;
                {;
                    { "231", "Potraživanja za kamatu od finansijske imovine i zateznu kamatu" }, ;
                    { "2310", "Potraživanja za kamatu po depozitima po amortizovanom trošku" }, ;
                    { "2311", "Potraživanja za kamatu po datim kreditima po amortizovanom trošku" }, ;
                    { "2312", "Potraživanja za kamatu po obveznicama po amortizovanom trošku" }, ;
                    { "2313", "Potraživanja za kamatu po ostaloj finansijskoj imovini po amortizovanom trošku" }, ;
                    { "2314", "Potraživanja za zateznu kamatu" } ;
                };
            },;
            { "231", "Potraživanja za kamatu i dividendu od drugih subjekata", ;
                {;
                    { "230", "Potraživanja za dividende" } ;
                };
            },;
            { "240", "Kratkoročni krediti povezanim pravnim licima", ;
                {;
                    { "2402", "Dati krediti" } ;
                };
            },;
            { "29", "Gubitak iznad visine kapitala", ;
                {;
                    { "35", "Gubitak" }, ;
                    { "350", "Gubitak ranijih perioda" }, ;
                    { "351", "Gubitak izvještajnog perioda" } ;
                };
            },;
            { "290", "Gubitak iznad visine kapitala", ;
                {;
                    { "35", "Gubitak" }, ;
                    { "350", "Gubitak ranijih perioda" }, ;
                    { "351", "Gubitak izvještajnog perioda" } ;
                };
            },;
            { "303", "Zadružni udjeli", ;
                {;
                    { "X303", "X? Zadružni udjeli" } ;
                };
            },;
            { "304", "Ulozi", ;
                {;
                    { "X304", "X? Ulozi" } ;
                };
            },;
            { "31", "Upisani neuplaćeni kapital", ;
                {;
                    { "23", "Ostala kratkoročna potraživanja"},;
                    { "231", "Potraživanja za kamatu od finansijske imovine i zateznu kamatu" }, ;
                    { "2310", "Potraživanja za kamatu po depozitima po amortizovanom trošku" }, ;
                    { "2311", "Potraživanja za kamatu po datim kreditima po amortizovanom trošku" }, ;
                    { "2312", "Potraživanja za kamatu po obveznicama po amortizovanom trošku" }, ;
                    { "2313", "Potraživanja za kamatu po ostaloj finansijskoj imovini po amortizovanom trošku" }, ;
                    { "2314", "Potraživanja za zateznu kamatu" } ;
                };
            },;
            { "310", "Upisane neuplaćene dionice", ;
                {;
                    { "23", "Ostala kratkoročna potraživanja"},;
                    { "231", "Potraživanja za kamatu od finansijske imovine i zateznu kamatu" }, ;
                    { "2310", "Potraživanja za kamatu po depozitima po amortizovanom trošku" }, ;
                    { "2311", "Potraživanja za kamatu po datim kreditima po amortizovanom trošku" }, ;
                    { "2312", "Potraživanja za kamatu po obveznicama po amortizovanom trošku" }, ;
                    { "2313", "Potraživanja za kamatu po ostaloj finansijskoj imovini po amortizovanom trošku" }, ;
                    { "2314", "Potraživanja za zateznu kamatu" } ;
                };
            },;
            { "312", "Upisani neuplaćeni udjeli", ;
                {;
                    { "23", "Ostala kratkoročna potraživanja"},;
                    { "231", "Potraživanja za kamatu od finansijske imovine i zateznu kamatu" }, ;
                    { "2310", "Potraživanja za kamatu po depozitima po amortizovanom trošku" }, ;
                    { "2311", "Potraživanja za kamatu po datim kreditima po amortizovanom trošku" }, ;
                    { "2312", "Potraživanja za kamatu po obveznicama po amortizovanom trošku" }, ;
                    { "2313", "Potraživanja za kamatu po ostaloj finansijskoj imovini po amortizovanom trošku" }, ;
                    { "2314", "Potraživanja za zateznu kamatu" } ;
                };
            },;
            { "319", "Ostali upisani neuplaćeni kapital", ;
                {;
                    { "23", "Ostala kratkoročna potraživanja"},;
                    { "231", "Potraživanja za kamatu od finansijske imovine i zateznu kamatu" }, ;
                    { "2310", "Potraživanja za kamatu po depozitima po amortizovanom trošku" }, ;
                    { "2311", "Potraživanja za kamatu po datim kreditima po amortizovanom trošku" }, ;
                    { "2312", "Potraživanja za kamatu po obveznicama po amortizovanom trošku" }, ;
                    { "2313", "Potraživanja za kamatu po ostaloj finansijskoj imovini po amortizovanom trošku" }, ;
                    { "2314", "Potraživanja za zateznu kamatu" } ;
                };
            },;
            { "333", "Nerealizovani gubici iz osnova finansijskih sredstava raspoloživih za prodaju", ;
                {;
                    { "X333", "X? Nerealizovani gubici iz osnova finansijskih sredstava raspoloživih za prodaju" } ;
                };
            },;
            { "342", "neraspoređeni višak prihoda ranijih godina", ;
                {;
                    { "340", "Neraspoređena dobiti ranijih perioda" } ;
                };
            },;
            { "343", "neraspoređeni višak prihoda ranijih godina", ;
                {;
                    { "341", "Neraspoređena dobit izvještajnog perioda" } ;
                };
            },;
            { "411", "Dugoročne obaveze prema povezanim pravnim licima", ;
                {;
                    { "410", "Obaveze koje se mogu konvertovati u kapital" }, ;
                    { "412", "Obaveze po izdatim dužničkim instrumentima" }, ;
                    { "413", "Dugoročni krediti uzeti u zemlji" }, ;
                    { "414", "Dugoročni krediti uzeti u inostranstvu" }, ;
                    { "415", "Dugoročne obaveze po najmovima (finansijski najam)" }, ;
                    { "416", "Dugoročne obaveze po najmovima (operativni najam)" }, ;
                    { "418", "Ostale dugoročne finansijske obaveze po amortizovanom trošku" }, ;
                    { "419", "Ostale dugoročne obaveze" } ;
                };
            },;
            { "415", "lizing u zemlji", ;
                {;
                    { "415", "Dugoročne obaveze po najmovima (finansijski najam)" }, ;
                    { "416", "Dugoročne obaveze po najmovima (operativni najam)" } ;
                };
            },;
            { "416", "lizing u inostranstvu", ;
                {;
                    { "415", "Dugoročne obaveze po najmovima (finansijski najam)" }, ;
                    { "416", "Dugoročne obaveze po najmovima (operativni najam)" } ;
                };
            },;
            { "420", "obaveze prema povezaznim pravnim licima", ;
                {;
                    { "421", "Obaveze po izdatim dužničkim instrumentima" }, ;
                    { "422", "Kratkoročni krediti uzeti u zemlji" }, ;
                    { "423", "Kratkoročni krediti uzeti u inostranstvu" }, ;
                    { "424", "Prekoračenja po bankovnim računima" }, ;
                    { "425", "Kratkoročne obaveze po najmovima (finansijski najam)" }, ;
                    { "426", "Kratkoročne obaveze po najmovima (operativni najam)" }, ;
                    { "428", "Ostale kratkoročne finansijske obaveze po amortizovanom trošku" } ;
                };
            },;
            { "424", "Kratkoročni dio dugoročnih kredita", ;
                {;
                    { "422", "Kratkoročni krediti uzeti u zemlji" }, ;
                    { "423", "Kratkoročni krediti uzeti u inostranstvu" } ;
                };
            },;
            { "430", "Primljeni avansi, depoziti i kaucije", ;
                {;
                    { "430", "Primljeni depoziti i kaucije i zadržana plaćanja" }, ;
                    { "434", "Primljeni avansi" }, ;
                    { "435", "Obaveze po programu lojalnosti kupaca" }, ;
                    { "437", "Obaveze po osnovu faktoring poslova" } ;
                };
            },;
            { "44", "Obaveze iz specifičnih poslova", ;
                {;
                    { "X44", "X? Obaveze iz specifičnih poslova" } ;
                };
            },;
            { "62", "Prihodi od aktiviranja ili potrošnje robe i učinaka", ;
                {;
                    { "X62", "X? Prihodi od aktiviranja ili potrošnje robe i učinaka" } ;
                };
            },;
            { "642", "Povećanje vrijednosti ostalih specifičnih sredstava koja se ne amortizuju", ;
                {;
                    { "640", "Povećanje fer vrijednosti investicijskih nekretnina koja se ne amortizuju" } ;
                };
            },;
            { "645", "Smanjenje vrijednosti ostalih specifičnih sredstava koja se ne amortizuju", ;
                {;
                    { "643", "Smanjenje fer vrijednosti investicijskih nekretnina koja se ne amortizuju" } ;
                };
            },;
            { "660", "Finansijski prihodi od povezanih pravnih lica", ;
                {;
                    { "656", "Prihodi od dividendi" } ;
                };
            },;
            { "664", "Prihodi od učešća u dobiti zajedničkih ulaganja", ;
                {;
                    { "X664", "X? Prihodi od učešća u dobiti zajedničkih ulaganja" } ;
                };
            },;
        }


    IF hb_HHasKey( my_server_params(), "database" )
        cDatabase := my_server_params()[ "database" ]
    ENDIF


    if Right(cDatabase, 4) == "2021"
        //
        Alert("nalazimo se u bazi 2021")
    ENDIF


    return .T.


