trigger:
  branches:
    include:
    - 4
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - CHANGELOG.md


variables:
- group: API_KEYS

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: hernad/azure-linux-build-agent:ia32

jobs:
- job: Linux_x64_Centos7
  # centos 7
  pool: default
  variables:
    BUILD_ARCH: x64
  steps:
  - script: |
      cd $(Build.SourcesDirectory)
      ./azure-build-linux-rhel.sh
    displayName: CI-Build F18 64-bit RHEL/CENTOS7 linux
  - script: |
      cd $(Build.SourcesDirectory)
      ./upload_localhost.sh
    displayName: upload F18-linux-x64 version $(BUILD.BUILDNUMBER)
    env:
      BINTRAY_API_KEY: $(BINTRAY_BRINGOUT_API_KEY)

