trigger:
  branches:
    include:
    - 4
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - CHANGELOG.md


variables:
- group: API_KEYS

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: hernad/azure-linux-build-agent:ia32

jobs:
- job: Windows_x64_local_windows
  pool: windows
  #  vmImage: VS2017-Win2016
  variables:
    VSCODE_ARCH: x86
    BINTRAY_ARCH: x86
  steps:
    - task: NodeTool@0
      inputs:
         versionSpec: "12.14.0"
    - script: |
        azure-build-win32-msvc.bat
      displayName: Build F18 windows 32-bit
      env:
        CHERE_INVOKING: yes
    - script: |
        upload_bintray_win32.bat
      displayName: upload F18-windows-x86 version $(BUILD.BUILDNUMBER)
      env:
        CHERE_INVOKING: yes
        BINTRAY_API_KEY: $(BINTRAY_BRINGOUT_API_KEY)
