trigger:
  branches:
    include:
    - 4
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - CHANGELOG.md


variables:
- group: API_KEYS

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: hernad/azure-linux-build-agent:ia32

jobs:
- job: Linux_x64
  pool: local-dell-xps15
  container: vscode-ia32
  variables:
    BUILD_ARCH: x64
    BINTRAY_ARCH: x64
    MINGW_ARCH: x86_64
  steps:
  - script: |
      cd $(Build.SourcesDirectory)
      ./ci-build-linux.sh
    displayName: CI-Build F18 64-bit
  - script: |
      cd $(Build.SourcesDirectory)
      ./upload_localhost.sh
    displayName: upload F18-linux-x64 version $(BUILD.BUILDNUMBER)
    env:
      BINTRAY_API_KEY: $(BINTRAY_BRINGOUT_API_KEY)
