CREATE SCHEMA IF NOT EXISTS {{ ansible_nodename }};

DROP ROLE IF EXISTS xtrole;
CREATE ROLE xtrole NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT ALL ON SCHEMA {{ ansible_nodename }} TO xtrole;
ALTER ROLE admin SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

GRANT xtrole TO admin;
GRANT xtrole TO {{ ansible_nodename }};
