CREATE ROLE xtrole
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT ALL ON SCHEMA {{ item.name }}  TO xtrole;

ALTER ROLE admin
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
GRANT xtrole TO admin;

GRANT xtrole TO {{ item.name }};
