CREATE SCHEMA IF NOT EXISTS f18;
CREATE SCHEMA IF NOT EXISTS fmk;

DROP ROLE IF EXISTS xtrole;
CREATE ROLE xtrole NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT ALL ON SCHEMA f18 TO xtrole;
GRANT ALL ON SCHEMA fmk TO xtrole;

ALTER ROLE admin SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

GRANT xtrole TO admin;

-- user npr. knjig pripada grupi xtrole;
GRANT xtrole TO {{ db_user }};


