CREATE SCHEMA IF NOT EXISTS f18;

DROP ROLE IF EXISTS xtrole;
CREATE ROLE xtrole NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT ALL ON SCHEMA f18 TO xtrole;
GRANT ALL ON SCHEMA fmk TO xtrole;

ALTER ROLE admin SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

GRANT xtrole TO admin;

GRANT xtrole TO f18;
GRANT xtrole TO fmk;

