DO $$
BEGIN

CREATE PUBLICATION f18_sifre;
ALTER PUBLICATION f18_sifre ADD TABLE f18.valute;
ALTER PUBLICATION f18_sifre ADD TABLE f18.partn;
ALTER PUBLICATION f18_sifre ADD TABLE f18.tarifa;
ALTER PUBLICATION f18_sifre ADD TABLE f18.sifk;
ALTER PUBLICATION f18_sifre ADD TABLE f18.sifv;


EXCEPTION WHEN OTHERS THEN
   RAISE INFO 'f18_sifre publikacija postoji replikaciju postoji';
END;
$$;

