---
# tasks file for roles/basic

- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present

- name: upgrade all packages
  yum: name=* state=latest

- name: Install common software requirements
  ignore_errors: yes
  become: true
  yum: pkg={{ item }} state=present
  with_items:
          - vim
          - curl
          - wget
          - ntp
          - rsync
          - rdiff-backup
          - p7zip
          - p7zip-plugins
          - yum-plugin-fastestmirror
          - epel-release
          - htop
          - tcpdump
          - traceroute
          - net-tools
          - bind-utils
          - docker
          - docker-compose
          - mdadm
          - telnet
          - bridge-utils
          - python-pip
          - the_silver_searcher
          - tmux


- name: add group docker
  group: name=docker state=present

- name: Adding bringout user to group docker
  user: name=bringout
        groups=docker
        append=yes

- name: install pexpect
  pip:
    name: pexpect
  become: yes

- name: set timezone to Europe/Sarajevo
  timezone:
    name: Europe/Sarajevo
