filegroup(
    name = "headers",
    srcs = glob([
        "*.zhh",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "headers_filegroup",
    srcs = glob([
        "*.zhh",
    ]),
    visibility = ["//visibility:public"],
)